repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: black .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: ruff
        name: ruff
        entry: ruff .
        language: system
        types: [ python ]
        pass_filenames: false